---
title: "Pairwise and overall Fst with confidence intervals + building phylogenetic tree"
author: "Thierry Gosselin"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
# output: 
# pdf_document:
vignette: >
  %\VignetteIndexEntry{Pairwise and overall Fst with confidence intervals + building phylogenetic tree}
    %\VignetteEngine{knitr::rmarkdown}
    \usepackage[utf8]{inputenc}
---
    
```{r, echo = FALSE, message = FALSE}
    knitr::opts_chunk$set(collapse = T, comment = "#>")
    options(tibble.print_min = 4L, tibble.print_max = 4L)
```
    
# Objectives
  * learn how to run the function `assigner::fst_WC84`
  * compute pairwise and overall Weir and Cockerham (1984) Fst estimates
  * build confidence intervals
  * visualize the estimates with data frame and matrices
  * learn how to integrate the function with other package, e.g. to build a phylogenetic tree
  * make Louis Bernatchez happy !
  
# Special concerns for genome-wide estimate and filtering bias 
During computation, the function first starts by keeping only the polymorphic
markers in common between the populations. 

When your project involves > 2 populations that evolved more by neutral processes
(e.g. genetic drift) than by natural selection, filtering to keep only the markers 
in common between your populations will drastically reduce the number of markers, 
and consequently your genome coverage for the estimate. Strategically, you should
reduce the threshold of number of populations required to keep a marker 
(e.g. use a minimum of 2 populations genotyped for the markers to keep it). 
This is easily tested with `stackr::filter_population` or in 
stacks population module.

The overall fst and fis estimates will have reduce genome-wide coverage, 
because the computation is conducted with shared markers accross 
all your populations. However, for the pairwise comparisons, the markers will be
tallied automatically for the pair. This usually results in more legitimate markers 
(i.e. less filtering bias) being used during computation, 
providing better genome-wide estimates for that pair.

# Workflow

## Fst calculations

1. Clean your desk and remove the clutter in the global environment
```r
rm(list=ls())
```

1. Automatically install/load the required libraries
```r
if (!require("pacman")) install.packages("pacman")
library("pacman")
pacman::p_load(devtools, reshape2, ggplot2, stringr, stringi, plyr, dplyr, tidyr, readr, purrr, data.table, ape)
if (!require("stackr")){
  install_github("thierrygosselin/stackr", build_vignettes = TRUE)
  library("stackr")
}
if (!require("assigner")) {
  install_github("thierrygosselin/assigner", build_vignettes = TRUE)
  #install_gsi_sim(fromSource = TRUE) # if assigner was re-installed, uncomment and run
  library("assigner")
}
```

1. Get the data:
```r
data.fst <- read_tsv(file = "https://raw.githubusercontent.com/thierrygosselin/package_data/master/assigner_data_fst.tsv.gz")
```

1. `fst_WC84` first run:  overall and pairwise, but without boostrap (i.e. no confidence intervals)
```r
fst <- fst_WC84(data = data.fst, 
pop.levels = c("pop1", "pop2", "pop3", "pop4", "pop5", "pop6", "pop7", "pop8", "pop9", "pop10", "pop11"),
holdout.samples = NULL,
pairwise = TRUE,
ci = FALSE, 
digits = 6,
verbose = TRUE
)
```

1. The results in the console:
```r
#######################################################################
######################### assigner::fst_WC84 ##########################
#######################################################################
Importing data
Computing global fst
Computing paiwise fst
############################### RESULTS ###############################
Fst (overall): 0.052428
#######################################################################
```

1. To view the content of `fst`:
```r
names(fst)
```

1. Get access to specific content with `$`:
    * `$sigma.loc`: the variance components per locus: 
   `lsiga`: among populations, 
   `lsigb`: among individuals within populations, 
   `lsigw`: within individuals.
   
    * `$fst.markers`: the fst by markers
    * `$fst.ranked`: the fst ranked
    * `$fst.overall`: the mean fst overall markers and number of markers 
    * `$fis.markers`: the fis by markers 
    * `$fis.overall`: the mean fis overall markers and number of markers 
    * `$fst.plot`: the histogram of the overall Fst per markers
    * `$pairwise.fst`: the pairwise fst in long/tidy data frame and number of markers per pairwise comparison
    * `$pairwise.fst.upper.matrix`: the pairwise fst in a upper triangle matrix
    * `$pairwise.fst.full.matrix`: the pairwise fst matrix (duplicated upper and lower triangle)
    * `$pairwise.fst.ci.matrix`: matrix with pairwise fst in the upper triangle
 and the confidence intervals in the lower triangle.


1. The data frame with pairwise fst values:
```r
df <- fst$pairwise.fst
```

1. The first 10 parwise comparisons in `df`:

| POP1 | POP2  |  FST   | N_MARKERS |
|:----:|:-----:|:------:|:---------:|
| pop1 | pop2  | 0.0442 |   3457    |
| pop1 | pop3  | 0.0507 |   3457    |
| pop1 | pop4  | 0.0341 |   3457    |
| pop1 | pop5  | 0.0300 |   3457    |
| pop1 | pop6  | 0.0434 |   3457    |
| pop1 | pop7  | 0.0367 |   3457    |
| pop1 | pop8  | 0.0256 |   3457    |
| pop1 | pop9  | 0.0475 |   3457    |
| pop1 | pop10 | 0.0522 |   3457    |
| pop1 | pop11 | 0.0473 |   3457    |

10. The matrix with fst values:
```r
fst.matrix <- fst$pairwise.fst.full.matrix
# as a data frame
fst.matrix <- data.frame(fst$pairwise.fst.full.matrix) %>% add_rownames("POP")
```
1. If you try to get the `pairwise.fst.ci.matrix`:
```r
fst$pairwise.fst.ci.matrix # you will get this:
[1] "pairwise fst not selected"
```

1. So let's make another run with `fst_WC84`, but this time will ask for the confidence intervals:
```r
fst.ci <- fst_WC84(data = data.fst, 
pop.levels = c("pop1", "pop2", "pop3", "pop4", "pop5", "pop6", "pop7", "pop8", "pop9", "pop10", "pop11"),
holdout.samples = NULL,
pairwise = TRUE,
ci = TRUE, 
iteration.ci = 100,
quantiles.ci = c(0.025, 0.975),
digits = 6,
parallel.core = 8,
verbose = TRUE
)
```

1. Try again to get the matrix with fst and ci:
```r
fst.ci$pairwise.fst.ci.matrix
```

1. To have this in a handy table for publication, we will create a new object `pairwise.fst.ci.df`:
```r
pairwise.fst.ci.df <- data.frame(fst.ci$pairwise.fst.ci.matrix) %>% add_rownames("POP")
# if you have numeric pop_id identifier you might have to do this to get proper column names:
colnames(pairwise.fst.ci.df) <- colnames(fst.ci$pairwise.fst.ci.matrix)
# to save:
write_tsv(x = pairwise.fst.ci.df, path = "pairwise.fst.ci.df.tsv")
```

## Phylogenetic tree
For the next steps, we need the full distance matrix created in step 10.

1. For a Neighbor joining tree:
```r
# build the tree:
tree <- nj(X = fst.matrix)
# for annotating bootstraps values on the tree:
bootstrap.value <- boot.phylo(phy = tree, x = fst.matrix, FUN = function (x) nj(x), block = 1, B = 10000, trees = FALSE, rooted = FALSE)
 # to get percentage values
bootstrap.value <- round((bootstrap.value/10000)*100, 0)
bootstrap.value
# to include in the tree
tree$node.label <- bootstrap.value 
```

1. For a UPGMA tree:
```r
tree <- as.phylo(hclust(dist(fst.matrix), method = "average"))
bootstrap.value <- boot.phylo(phy = tree, x = fst.matrix, FUN = function (xx) as.phylo(hclust(dist(xx), method = "average")) , block = 1, B = 10000, trees = FALSE, rooted = TRUE) 
bootstrap.value <- round((bootstrap.value/10000)*100, 0)
bootstrap.value
tree$node.label <- bootstrap.value
```

1. To build the tree we will need to install \pkg{ggtree}
```r
# get the latest development version of ggtree:
if (!require("ggtree")) install_github("GuangchuangYu/ggtree")
```

1. if it doesn't work after this, you might need to install dependencies. And 
you might have to install them (see [bioconductor](https://bioconductor.org/packages/release/bioc/html/ggtree.html)).

    * **Imports:** ape, Biostrings, grDevices, grid, jsonlite, magrittr, methods, stats4, tidyr, utils,
    * **Suggests:** colorspace, EBImage, knitr, phylobase, phytools, phangorn, rmarkdown, scales, testthat

1. To install **bioconductor** packages, you need to install this:
```r
## try http:// if https:// URLs are not supported
source("https://bioconductor.org/biocLite.R")
biocLite()
```

1. Build a very basic tree figure:
```r
library(ggtree)
tree.figure <- ggplot(tree, aes(x, y), ladderize = TRUE) + 
geom_tree() + 
# geom_tiplab(size = 3, hjust = -0.05, vjust = 0.5)+ # for just the tip label
geom_text(aes(label = label), size = 3, hjust = -0.05, vjust = 0.5) + # for both tips and nodes
theme_tree() + 
xlim(0, 0.16) # to allocate more space for tip labels (trial/error)
tree.figure
ggsave(filename = "assigner.fst.tree.example.pdf", width = 15, height = 15, dpi = 600, units = "cm", useDingbats = F)
```

1. Several vignettes are available to get to know [ggtree](http://guangchuangyu.github.io/ggtree/)


# Conclusion
Under construction

Please send me suggestions and bug reports through github

**References**

Weir BS, Cockerham CC (1984) Estimating F-Statistics for the 
Analysis of Population Structure. Evolution, 38, 1358–1370.

G Yu, D Smith, H Zhu, Y Guan, TTY Lam,
ggtree: an R package for visualization and annotation of phylogenetic tree with different types of meta-data.
revised.


