# remove NOTE about no visible binding for global variable during R CMD check --
if (getRversion() >= "2.15.1") {
  utils::globalVariables(
    c("ID", "#CHROM", "CHROM", "FORMAT", "INDIVIDUALS", "FORMAT_ID", "LOCUS",
      "POS", "REF", "ALT", "POP_ID", "READ_DEPTH", "ALLELE_DEPTH", "GL",
      "ERASE", "GT", "MARKERS", "QQ", "PQ", "N", "MAF_GLOBAL", "MAF_LOCAL",
      "ALLELES", "POP_ID", "GT", "INDIVIDUALS", "MARKERS", "POP_ID",
      "ALLELES_GROUP", "ALLELES", "N_IND_GENE", "P", "N",
      "het", "dum", "RANKING",
      "dum1", "SSG", "SSP", "SSi", "MSI", "sigw", "MSP",
      "siga", "sigb", "lsiga", "lsigb", "lsigw", "FST", "MARKERS",
      "MARKERS_ALLELES", "ALLELES", "POP_ID", "INDIVIDUALS", "filename",
      "ID", "KEEPER", "ASSIGN", "OTHERS", "CURRENT", "INFERRED",
      "SECOND_BEST_POP", "SCORE", "SECOND_BEST_SCORE", "NUMBER", "INDIVIDUALS_ALLELES",
      "MARKER_NUMBER", "MISSING_DATA", "TOTAL", "ASSIGNMENT_PERC",
      "MARKERS", "MISSING_DATA",
      "ITERATIONS", "METHOD", "TOTAL", "MEAN_i", "MEAN", "ASSIGNMENT_PERC",
      "SE", "MEDIAN", "MIN", "MAX", "QUANTILE25", "QUANTILE75", "SE_MIN",
      "SE_MAX", ".", "QUAL", "FILTER", "INFO", "pb", "SUBSAMPLE", "STRATA",
      "sum.pop", "A1", "A2", "INDIVIDUALS_2", "Cnt", "Catalog ID", "GROUP",
      "COUNT", "MAX_COUNT_MARKERS", "hierarchy", "GT_VCF", "ANALYSIS",
      "MEAN_ITERATIONS", "MEAN_SUBSAMPLE", "NUMBER_ITERATIONS",
      "NUMBER_SUBSAMPLE", "TOTAL_ITERATIONS", "TOTAL_SUBSAMPLE", "X1", "X2",
      "strata.df", "GENOTYPE", "FIS", "POP1", "POP2", "tsiga", "tsigb", "tsigw",
      "CI", "CI_LOW", "CI_HIGH", "N_MARKERS","sigma.loc.alleles", "DST", "DST_P",
      "FIS_CI_HIGH", "FIS_CI_LOW", "HO", "HS", "HT", "HT_P", "JOST_D", "MHO",
      "MN", "MP", "MP2", "MSP2", "NEI_FST", "NEI_FST_CI_HIGH", "NEI_FST_CI_LOW",
      "NEI_FST_P", "NEI_FST_P_CI_HIGH", "NEI_FST_P_CI_LOW", "NP", "N_INV",
      "SHO", "SP2", "n.markers", "JOST_D_CI_LOW", "JOST_D_CI_HIGH",
      "NEW_MARKERS", "PHI", "PHI_CI_HIGH", "PHI_CI_LOW", "PHI_PRIME",
      "PHI_PRIME_CI_HIGH", "PHI_PRIME_CI_LOW", "DATA", "ID1", "ID2", "DISTANCE",
      "nn", "maxsdap", "ID1_POP", "POP_COMP", "AMOVA", "F_STATS", "MC_ITERATIONS",
      "MODEL_VALUE", "OBS_VALUE", "SIGMA2A", "SIGMA2A_PRIME", "SIGMA2B",
      "VARIANCE", "global_boot", "iteration", "MARKERS_COMMON",
      "MEAN_MARKERS_COMMON", "FREQ_AL", "FREQ_APL", "MHOM", "NAPL", "NC", "NIL",
      "NIPL", "NIPL_SQ", "NIPL_SQ_SUM", "NPL", "V1", "V2", "Fst", "GT_BIN",
      "Current", "DLR", "DLR_RELATIVE", "Inferred", "Lik_home", "Lik_max",
      "Lik_ratio", "RATIO", "Individual", "Populations", "pop.labels",
      "filter.monomorphic", "LOW", "NS", "POP3", "blacklist.id",
      "holdout.samples", "ALLELE_GROUP", "MARKERS1", "fst.overall",
      "whitelist.markers", "random.seed", "folder", ".data", "MARKERS...1",
      "MARKERS...3", "MARKERS...4", "STRATA_SEQ", "ARGUMENTS", "VALUES",
      "input", "HET", "calibrate.alleles", "iteration.subsample", "n",
      "M_SEQ", "ID_SEQ", "1", "2", "where"
    )
  )
}
