pairwise.fst.full.matrix <- "spis_stats_fst_WC84_20201024@1437/pairwise.fst.full.matrix.RData"
pairwise.fst.ci.matrix <- "spis_stats_fst_WC84_20201024@1437/pairwise.fst.ci.matrix.RData"
digits = 4
path.folder = "/Users/thierry/Dropbox/partage/partage_carol/fst_20201020"
filename = "test"
n.s = TRUE
digits = 5
color.low = "blue"
color.mid = "yellow"
color.high = "red"
text.size = 4
plot.size = 40
pop.levels = NULL
